<script setup lang="ts">
import { UvAlert,UvBadge,UvButton,UvInput,UvSwitch } from '@universal-vue/vue'
import { UvIcon } from '@universal-vue/icons'
const projectName=ref('Universal Vue');const enabled=ref(true)
useSeoMeta({title:'Free Vue components for every framework',description:'Build once in Vue and use the same accessible components in Vue, React, Angular, Svelte, Laravel, WordPress, and plain HTML.'})
const features=[
 {icon:'V',title:'Native Vue',text:'Typed Vue 3 components with props, events, slots, plugin installation, and tree-shakable imports.'},
 {icon:'<>',title:'Custom Elements',text:'Standards-based elements for React, Angular, Svelte, server-rendered templates, and plain HTML.'},
 {icon:'CDN',title:'No-build CDN',text:'Browser-ready bundles published from the same npm release for prototypes and simple websites.'}
]
</script>
<template><div>
<section class="hero"><div class="site-container hero-grid"><div><span class="eyebrow"><UvBadge tone="success" pill dot>Open source alpha</UvBadge></span><h1>One component library.<br><span class="gradient-text">Every web stack.</span></h1><p>Create accessible interfaces with Vue 3, then deliver the same components as native Vue packages, Custom Elements, and CDN bundles.</p><div class="hero-actions"><NuxtLink class="link-button link-button--primary link-button--lg" to="/docs/installation">Get started <UvIcon name="arrowRight"/></NuxtLink><NuxtLink class="link-button link-button--outline link-button--lg" to="/components">Explore components</NuxtLink></div><div class="hero-stats"><div><strong>40</strong>accessible components</div><div><strong>6</strong>consumer examples</div><div><strong>MIT</strong>always free</div></div></div><div class="preview-window"><div class="preview-bar"><span/><span/><span/></div><div class="preview-body"><UvAlert tone="info" title="Real package preview">This UI is rendered from the same workspace package users install.</UvAlert><div class="preview-form"><UvInput v-model="projectName" label="Project name" clearable/><UvSwitch v-model="enabled" label="Enable framework adapters"/><UvButton>Publish component</UvButton></div></div></div></div></section>
<section class="section"><div class="site-container"><div class="section-heading"><span class="eyebrow">Three distributions</span><h2>Use the right delivery format without rebuilding your UI.</h2><p>Every public component starts from one Vue source and is validated through multiple consumer paths.</p></div><div class="card-grid"><article v-for="feature in features" :key="feature.title" class="feature-card"><div class="feature-icon">{{feature.icon}}</div><h3>{{feature.title}}</h3><p>{{feature.text}}</p></article></div></div></section>
<section class="section"><div class="site-container"><div class="section-heading"><span class="eyebrow">Designed for trust</span><h2>Free, testable, transparent.</h2></div><div class="card-grid"><article class="feature-card"><h3>Accessible by default</h3><p>Native controls, keyboard behavior, visible focus, semantic status announcements, and automated axe checks.</p></article><article class="feature-card"><h3>Typed and documented</h3><p>Component metadata drives API tables, search, and compatibility guidance so docs stay close to tested source.</p></article><article class="feature-card"><h3>Public release pipeline</h3><p>Changesets, package validation, local tarball tests, CI, npm provenance, and GitHub release automation are included.</p></article></div></div></section>
<section class="section"><div class="site-container content-card"><div class="section-heading"><span class="eyebrow">Ready to build</span><h2>Start locally, verify every package, then publish confidently.</h2><p>The repository includes the website, component source, distributions, examples, tests, CI, and release configuration.</p></div><div class="hero-actions"><NuxtLink class="link-button link-button--primary" to="/docs/installation">Read installation guide</NuxtLink><NuxtLink class="link-button link-button--ghost" to="/roadmap">View roadmap</NuxtLink></div></div></section>
</div></template>
