<script setup lang="ts">
import { computed, ref } from 'vue'
import type { UvNavigationMenuDetail,UvNavigationMenuItem,UvNavigationMenuId } from './navigation-menu.types'
interface Props { items?:UvNavigationMenuItem[]; itemsJson?:string; modelValue?:UvNavigationMenuId; label?:string; orientation?:'horizontal'|'vertical' }
const props=withDefaults(defineProps<Props>(),{items:()=>[],itemsJson:'',modelValue:undefined,label:'Primary navigation',orientation:'horizontal'})
const emit=defineEmits<{ 'update:modelValue':[id:UvNavigationMenuId]; select:[detail:UvNavigationMenuDetail] }>()
const open=ref<UvNavigationMenuId|null>(null)
function parse(){try{const v=JSON.parse(props.itemsJson);return Array.isArray(v)?v:[]}catch{return[]}}
const list=computed<UvNavigationMenuItem[]>(()=>props.items.length?props.items:parse())
function choose(item:UvNavigationMenuItem,event?:Event){if(item.disabled){event?.preventDefault();return}emit('update:modelValue',item.id);emit('select',{id:item.id,item});if(!item.children?.length)open.value=null}
function toggle(item:UvNavigationMenuItem){if(!item.disabled)open.value=open.value===item.id?null:item.id}
function key(event:KeyboardEvent,index:number){const buttons=[...(event.currentTarget as HTMLElement).closest('ul')?.querySelectorAll<HTMLButtonElement>(':scope > li > button,:scope > li > a')||[]];if(!['ArrowRight','ArrowLeft','Home','End'].includes(event.key))return;event.preventDefault();const next=event.key==='Home'?0:event.key==='End'?buttons.length-1:(index+(event.key==='ArrowRight'?1:-1)+buttons.length)%buttons.length;buttons[next]?.focus()}
</script>
<template><nav class="uv-navigation-menu" :class="`uv-navigation-menu--${orientation}`" :aria-label="label"><ul><li v-for="(item,index) in list" :key="item.id"><button v-if="item.children?.length" type="button" :disabled="item.disabled" :aria-expanded="open===item.id" @click="toggle(item)" @keydown="key($event,index)">{{ item.label }} <span aria-hidden="true">▾</span></button><a v-else :href="item.disabled?undefined:item.href||'#'" :aria-current="modelValue===item.id?'page':undefined" :aria-disabled="item.disabled||undefined" :tabindex="item.disabled?-1:undefined" @click="choose(item,$event)" @keydown="key($event,index)">{{ item.label }}</a><ul v-if="item.children?.length && open===item.id" class="uv-navigation-menu__panel"><li v-for="child in item.children" :key="child.id"><a :href="child.disabled?undefined:child.href||'#'" :aria-disabled="child.disabled||undefined" :tabindex="child.disabled?-1:undefined" @click="choose(child,$event)">{{ child.label }}</a></li></ul></li></ul></nav></template>
<style>.uv-navigation-menu{font:inherit}.uv-navigation-menu ul{display:flex;gap:.25rem;margin:0;padding:0;list-style:none}.uv-navigation-menu--vertical>ul{flex-direction:column}.uv-navigation-menu li{position:relative}.uv-navigation-menu a,.uv-navigation-menu button{display:flex;align-items:center;gap:.3rem;border:0;border-radius:.5rem;padding:.6rem .75rem;background:transparent;color:#334155;font:600 .9rem/1 system-ui;text-decoration:none;cursor:pointer}.uv-navigation-menu a:hover,.uv-navigation-menu button:hover,.uv-navigation-menu a[aria-current=page]{background:#f1f5f9;color:var(--uv-color-primary,#2563eb)}.uv-navigation-menu a:focus-visible,.uv-navigation-menu button:focus-visible{outline:2px solid var(--uv-color-primary,#2563eb)}.uv-navigation-menu__panel{position:absolute!important;z-index:20;top:calc(100% + .35rem);left:0;display:grid!important;min-width:12rem;padding:.35rem!important;border:1px solid var(--uv-color-border,#cbd5e1);border-radius:.6rem;background:#fff;box-shadow:0 14px 35px #0f172a22}.uv-navigation-menu [aria-disabled=true],.uv-navigation-menu :disabled{opacity:.45;cursor:not-allowed}</style>
