<script setup lang="ts">
import { computed, ref } from 'vue'
import type { UvTransferListDetail,UvTransferListId,UvTransferListItem } from './transfer-list.types'
interface Props { items?:UvTransferListItem[]; itemsJson?:string; modelValue?:UvTransferListId[]; valuesJson?:string; sourceLabel?:string; targetLabel?:string; searchable?:boolean; disabled?:boolean }
const props=withDefaults(defineProps<Props>(),{items:()=>[],itemsJson:'',modelValue:undefined,valuesJson:'',sourceLabel:'Available',targetLabel:'Selected',searchable:true,disabled:false})
const emit=defineEmits<{ 'update:modelValue':[value:UvTransferListId[]]; change:[detail:UvTransferListDetail] }>()
const sourceSelection=ref<UvTransferListId[]>([]);const targetSelection=ref<UvTransferListId[]>([]);const sourceQuery=ref('');const targetQuery=ref('')
function parseArray(json:string){try{const v=JSON.parse(json);return Array.isArray(v)?v:[]}catch{return[]}}
const all=computed<UvTransferListItem[]>(()=>props.items.length?props.items:parseArray(props.itemsJson))
const values=computed<UvTransferListId[]>(()=>props.modelValue??parseArray(props.valuesJson))
const source=computed(()=>all.value.filter(i=>!values.value.includes(i.id)&&(!sourceQuery.value||i.label.toLowerCase().includes(sourceQuery.value.toLowerCase()))))
const target=computed(()=>all.value.filter(i=>values.value.includes(i.id)&&(!targetQuery.value||i.label.toLowerCase().includes(targetQuery.value.toLowerCase()))))
function toggle(bucket:'source'|'target',id:UvTransferListId){const list=bucket==='source'?sourceSelection:targetSelection;list.value=list.value.includes(id)?list.value.filter(v=>v!==id):[...list.value,id]}
function move(direction:'to-target'|'to-source'){if(props.disabled)return;const moved=(direction==='to-target'?sourceSelection.value:targetSelection.value).filter(id=>!all.value.find(i=>i.id===id)?.disabled);if(!moved.length)return;const value=direction==='to-target'?[...new Set([...values.value,...moved])]:values.value.filter(id=>!moved.includes(id));emit('update:modelValue',value);emit('change',{value,moved,direction});sourceSelection.value=[];targetSelection.value=[]}
</script>
<template><div class="uv-transfer-list" :aria-disabled="disabled||undefined"><section><label v-if="searchable"><span>{{ sourceLabel }}</span><input v-model="sourceQuery" type="search" :disabled="disabled" :placeholder="`Search ${sourceLabel.toLowerCase()}`"></label><h3 v-else>{{ sourceLabel }}</h3><div class="uv-transfer-list__list" role="listbox" :aria-label="sourceLabel" aria-multiselectable="true"><button v-for="item in source" :key="item.id" type="button" role="option" :aria-selected="sourceSelection.includes(item.id)" :disabled="disabled||item.disabled" @click="toggle('source',item.id)"><strong>{{ item.label }}</strong><span v-if="item.description">{{ item.description }}</span></button><p v-if="!source.length">No available items.</p></div></section><div class="uv-transfer-list__actions"><button type="button" :disabled="disabled||!sourceSelection.length" :aria-label="`Move selected to ${targetLabel}`" @click="move('to-target')">→</button><button type="button" :disabled="disabled||!targetSelection.length" :aria-label="`Move selected to ${sourceLabel}`" @click="move('to-source')">←</button></div><section><label v-if="searchable"><span>{{ targetLabel }}</span><input v-model="targetQuery" type="search" :disabled="disabled" :placeholder="`Search ${targetLabel.toLowerCase()}`"></label><h3 v-else>{{ targetLabel }}</h3><div class="uv-transfer-list__list" role="listbox" :aria-label="targetLabel" aria-multiselectable="true"><button v-for="item in target" :key="item.id" type="button" role="option" :aria-selected="targetSelection.includes(item.id)" :disabled="disabled||item.disabled" @click="toggle('target',item.id)"><strong>{{ item.label }}</strong><span v-if="item.description">{{ item.description }}</span></button><p v-if="!target.length">No selected items.</p></div></section></div></template>
<style>.uv-transfer-list{display:grid;grid-template-columns:minmax(0,1fr) auto minmax(0,1fr);gap:.75rem;align-items:center;font:inherit;color:#0f172a}.uv-transfer-list section{display:grid;gap:.45rem}.uv-transfer-list label{display:grid;gap:.35rem;font-weight:600}.uv-transfer-list input{padding:.6rem;border:1px solid var(--uv-color-border,#cbd5e1);border-radius:.45rem;font:inherit}.uv-transfer-list h3{margin:0;font-size:.95rem}.uv-transfer-list__list{min-height:12rem;max-height:18rem;overflow:auto;padding:.3rem;border:1px solid var(--uv-color-border,#cbd5e1);border-radius:var(--uv-radius-md,.625rem);background:#fff}.uv-transfer-list__list button{display:grid;width:100%;gap:.15rem;padding:.55rem .65rem;border:0;border-radius:.4rem;background:transparent;text-align:left;font:inherit;cursor:pointer}.uv-transfer-list__list button span{color:#64748b;font-size:.82rem}.uv-transfer-list__list button[aria-selected=true]{background:#dbeafe;color:#1d4ed8}.uv-transfer-list__list p{margin:.5rem;color:#64748b}.uv-transfer-list__actions{display:grid;gap:.45rem}.uv-transfer-list__actions button{width:2.4rem;height:2.4rem;border:1px solid var(--uv-color-border,#cbd5e1);border-radius:.5rem;background:#fff;font-size:1.1rem;cursor:pointer}.uv-transfer-list button:disabled{opacity:.45;cursor:not-allowed}@media(max-width:42rem){.uv-transfer-list{grid-template-columns:1fr}.uv-transfer-list__actions{grid-template-columns:1fr 1fr}.uv-transfer-list__actions button{width:100%}}</style>
