<script setup lang="ts">
interface Props { modelValue?:boolean; name?:string; label?:string; description?:string; disabled?:boolean; required?:boolean }
withDefaults(defineProps<Props>(),{modelValue:false,disabled:false,required:false});const emit=defineEmits<{ 'update:modelValue':[value:boolean]; change:[event:Event] }>()
function onChange(event:Event){emit('update:modelValue',(event.target as HTMLInputElement).checked);emit('change',event)}
</script>
<template><label class="uv-switch" :class="{'uv-switch--disabled':disabled}"><input class="uv-switch__native" type="checkbox" role="switch" :checked="modelValue" :name="name" :disabled="disabled" :required="required" @change="onChange"><span class="uv-switch__track" aria-hidden="true"><span class="uv-switch__thumb"/></span><span class="uv-switch__content"><span class="uv-switch__label"><slot>{{ label }}</slot></span><span v-if="description" class="uv-switch__description">{{ description }}</span></span></label></template>
<style>
.uv-switch{position:relative;display:inline-flex;align-items:flex-start;gap:.7rem;color:var(--uv-color-text,#0f172a);font-family:var(--uv-font-sans,system-ui,sans-serif);cursor:pointer}.uv-switch__native{position:absolute;opacity:0}.uv-switch__track{display:flex;align-items:center;flex:none;width:2.35rem;height:1.35rem;padding:.15rem;margin-top:.02rem;border-radius:999px;background:var(--uv-color-border-strong,#94a3b8);transition:.16s}.uv-switch__thumb{width:1.05rem;height:1.05rem;border-radius:50%;background:#fff;box-shadow:0 1px 3px rgb(15 23 42/.25);transition:transform .16s}.uv-switch__native:checked+.uv-switch__track{background:var(--uv-color-primary,#2563eb)}.uv-switch__native:checked+.uv-switch__track .uv-switch__thumb{transform:translateX(1rem)}.uv-switch__native:focus-visible+.uv-switch__track{box-shadow:var(--uv-focus-ring)}.uv-switch__content{display:grid;gap:.15rem}.uv-switch__label{font-size:.9375rem;font-weight:600}.uv-switch__description{font-size:.8125rem;color:var(--uv-color-text-muted,#64748b)}.uv-switch--disabled{opacity:.55;cursor:not-allowed}
</style>
