<script setup lang="ts">
import { computed, useId } from 'vue'
interface Props { modelValue?:string|number; id?:string; name?:string; label?:string; type?:string; placeholder?:string; hint?:string; error?:string; disabled?:boolean; readonly?:boolean; required?:boolean; clearable?:boolean; autocomplete?:string; min?:string|number; max?:string|number; step?:string|number }
const props=withDefaults(defineProps<Props>(),{modelValue:'',type:'text',disabled:false,readonly:false,required:false,clearable:false})
const emit=defineEmits<{ 'update:modelValue':[value:string]; input:[event:Event]; change:[event:Event]; focus:[event:FocusEvent]; blur:[event:FocusEvent]; clear:[] }>()
const generatedId=useId();const inputId=computed(()=>props.id??`uv-input-${generatedId}`);const hintId=computed(()=>props.hint?`${inputId.value}-hint`:undefined);const errorId=computed(()=>props.error?`${inputId.value}-error`:undefined);const describedBy=computed(()=>[hintId.value,errorId.value].filter(Boolean).join(' ')||undefined)
function onInput(event:Event){emit('update:modelValue',(event.target as HTMLInputElement).value);emit('input',event)}
function clear(){emit('update:modelValue','');emit('clear')}
defineExpose({focus:()=>document.getElementById(inputId.value)?.focus()})
</script>
<template><div class="uv-field"><label v-if="label" class="uv-field__label" :for="inputId">{{ label }} <span v-if="required" class="uv-field__required" aria-hidden="true">*</span></label><div class="uv-field__control" :class="{'uv-field__control--invalid':error}"><span v-if="$slots.prefix" class="uv-input__affix"><slot name="prefix"/></span><input :id="inputId" class="uv-field__input" :value="modelValue" :name="name" :type="type" :placeholder="placeholder" :disabled="disabled" :readonly="readonly" :required="required" :autocomplete="autocomplete" :min="min" :max="max" :step="step" :aria-invalid="error?true:undefined" :aria-describedby="describedBy" @input="onInput" @change="emit('change',$event)" @focus="emit('focus',$event)" @blur="emit('blur',$event)"/><button v-if="clearable&&String(modelValue).length&&!disabled&&!readonly" class="uv-input__clear" type="button" aria-label="Clear input" @click="clear">×</button><span v-if="$slots.suffix" class="uv-input__affix"><slot name="suffix"/></span></div><p v-if="hint&&!error" :id="hintId" class="uv-field__hint">{{ hint }}</p><p v-if="error" :id="errorId" class="uv-field__error" role="alert">{{ error }}</p></div></template>
<style>
@import '../shared.css';.uv-input__affix{display:inline-flex;align-items:center;padding-inline:.75rem;color:var(--uv-color-text-muted,#64748b)}.uv-input__clear{display:grid;place-items:center;flex:none;width:2rem;height:2rem;margin-right:.3rem;border:0;border-radius:50%;background:transparent;color:var(--uv-color-text-muted,#64748b);font-size:1.25rem}.uv-input__clear:hover{background:var(--uv-color-surface-subtle,#f8fafc)}.uv-input__clear:focus-visible{outline:0;box-shadow:var(--uv-focus-ring)}
</style>
