<script setup lang="ts">
import { computed } from 'vue'
import type { UvBottomNavigationDetail,UvBottomNavigationItem,UvBottomNavigationId } from './bottom-navigation.types'
interface Props { items?:UvBottomNavigationItem[]; itemsJson?:string; modelValue?:UvBottomNavigationId; label?:string; fixed?:boolean }
const props=withDefaults(defineProps<Props>(),{items:()=>[],itemsJson:'',modelValue:undefined,label:'Bottom navigation',fixed:false})
const emit=defineEmits<{ 'update:modelValue':[id:UvBottomNavigationId]; select:[detail:UvBottomNavigationDetail] }>()
function parse(){try{const v=JSON.parse(props.itemsJson);return Array.isArray(v)?v:[]}catch{return[]}}
const list=computed<UvBottomNavigationItem[]>(()=>props.items.length?props.items:parse())
function choose(item:UvBottomNavigationItem,event:Event){if(item.disabled){event.preventDefault();return}emit('update:modelValue',item.id);emit('select',{id:item.id,item})}
</script>
<template><nav class="uv-bottom-navigation" :class="{'uv-bottom-navigation--fixed':fixed}" :aria-label="label"><a v-for="item in list" :key="item.id" :href="item.disabled?undefined:item.href||'#'" :aria-current="modelValue===item.id?'page':undefined" :aria-disabled="item.disabled||undefined" :tabindex="item.disabled?-1:undefined" @click="choose(item,$event)"><span class="uv-bottom-navigation__icon" aria-hidden="true">{{ item.icon || '•' }}</span><span>{{ item.label }}</span><span v-if="item.badge!==undefined" class="uv-bottom-navigation__badge" :aria-label="`${item.badge} notifications`">{{ item.badge }}</span></a></nav></template>
<style>.uv-bottom-navigation{display:grid;grid-auto-flow:column;grid-auto-columns:1fr;max-width:36rem;border:1px solid var(--uv-color-border,#cbd5e1);border-radius:var(--uv-radius-md,.625rem);background:#fff;box-shadow:0 8px 24px #0f172a14;font:inherit}.uv-bottom-navigation--fixed{position:fixed;z-index:30;right:1rem;bottom:1rem;left:1rem;margin:auto}.uv-bottom-navigation a{position:relative;display:grid;justify-items:center;gap:.2rem;padding:.65rem .5rem;color:#64748b;font-size:.8rem;text-decoration:none}.uv-bottom-navigation a[aria-current=page]{color:var(--uv-color-primary,#2563eb)}.uv-bottom-navigation a:focus-visible{outline:2px solid var(--uv-color-primary,#2563eb);outline-offset:-2px}.uv-bottom-navigation__icon{font-size:1.1rem}.uv-bottom-navigation__badge{position:absolute;top:.25rem;left:55%;min-width:1.1rem;padding:.1rem .25rem;border-radius:999px;background:#dc2626;color:#fff;font-size:.65rem;text-align:center}.uv-bottom-navigation [aria-disabled=true]{opacity:.45;cursor:not-allowed}</style>
