<script setup lang="ts">
import { computed, nextTick, ref } from 'vue'
import type { UvSplitButtonItem,UvSplitButtonSelectDetail } from './split-button.types'
interface Props { label?:string; menuLabel?:string; items?:UvSplitButtonItem[]; itemsJson?:string; disabled?:boolean; modelValue?:boolean }
const props=withDefaults(defineProps<Props>(),{label:'Action',menuLabel:'More actions',items:()=>[],itemsJson:'',disabled:false,modelValue:false})
const emit=defineEmits<{ action:[MouseEvent]; select:[detail:UvSplitButtonSelectDetail]; 'update:modelValue':[open:boolean] }>()
const root=ref<HTMLElement|null>(null)
function parse(){try{const v=JSON.parse(props.itemsJson);return Array.isArray(v)?v:[]}catch{return[]}}
const list=computed<UvSplitButtonItem[]>(()=>props.items.length?props.items:parse())
function open(){emit('update:modelValue',true);nextTick(()=>root.value?.querySelector<HTMLButtonElement>('[role=menuitem]:not(:disabled)')?.focus())}
function close(focus=false){emit('update:modelValue',false);if(focus)nextTick(()=>root.value?.querySelector<HTMLButtonElement>('.uv-split-button__toggle')?.focus())}
function choose(item:UvSplitButtonItem){if(item.disabled)return;emit('select',{id:item.id,item});close(true)}
function key(event:KeyboardEvent){if(event.key==='Escape'){event.preventDefault();close(true)}else if(event.key==='ArrowDown'){event.preventDefault();const buttons=[...root.value?.querySelectorAll<HTMLButtonElement>('[role=menuitem]:not(:disabled)')||[]];const index=buttons.indexOf(event.target as HTMLButtonElement);buttons[(index+1)%buttons.length]?.focus()}else if(event.key==='ArrowUp'){event.preventDefault();const buttons=[...root.value?.querySelectorAll<HTMLButtonElement>('[role=menuitem]:not(:disabled)')||[]];const index=buttons.indexOf(event.target as HTMLButtonElement);buttons[(index-1+buttons.length)%buttons.length]?.focus()}}
</script>
<template><div ref="root" class="uv-split-button"><div class="uv-split-button__actions"><button type="button" class="uv-split-button__primary" :disabled="disabled" @click="emit('action',$event)"><slot>{{ label }}</slot></button><button type="button" class="uv-split-button__toggle" :disabled="disabled" :aria-expanded="modelValue" aria-haspopup="menu" :aria-label="menuLabel" @click="modelValue?close():open()">▾</button></div><div v-if="modelValue" class="uv-split-button__menu" role="menu" :aria-label="menuLabel" @keydown="key"><button v-for="item in list" :key="item.id" type="button" role="menuitem" :disabled="item.disabled" @click="choose(item)">{{ item.label }}</button><slot name="menu" /></div></div></template>
<style>.uv-split-button{position:relative;display:inline-block;font:inherit}.uv-split-button__actions{display:flex}.uv-split-button__actions button{border:1px solid var(--uv-color-primary,#2563eb);padding:.65rem .8rem;background:var(--uv-color-primary,#2563eb);color:#fff;font:600 .9rem/1 system-ui;cursor:pointer}.uv-split-button__primary{border-radius:var(--uv-radius-md,.625rem) 0 0 var(--uv-radius-md,.625rem)}.uv-split-button__toggle{border-left-color:#ffffff55!important;border-radius:0 var(--uv-radius-md,.625rem) var(--uv-radius-md,.625rem) 0}.uv-split-button__menu{position:absolute;z-index:20;top:calc(100% + .35rem);right:0;display:grid;min-width:12rem;padding:.3rem;border:1px solid var(--uv-color-border,#cbd5e1);border-radius:.55rem;background:#fff;box-shadow:0 12px 30px #0f172a22}.uv-split-button__menu button{border:0;border-radius:.4rem;padding:.6rem .7rem;background:transparent;text-align:left;font:inherit;cursor:pointer}.uv-split-button__menu button:hover,.uv-split-button__menu button:focus{background:#f1f5f9;outline:0}.uv-split-button button:disabled{opacity:.5;cursor:not-allowed}</style>
