<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import type { UvListboxDetail,UvListboxOption,UvListboxValue } from './listbox.types'
interface Props { modelValue?:UvListboxValue|UvListboxValue[]; options?:UvListboxOption[]; optionsJson?:string; multiple?:boolean; searchable?:boolean; label?:string; disabled?:boolean; size?:number }
const props=withDefaults(defineProps<Props>(),{modelValue:undefined,options:()=>[],optionsJson:'',multiple:false,searchable:false,label:'Choose an option',disabled:false,size:6})
const emit=defineEmits<{ 'update:modelValue':[value:UvListboxValue|UvListboxValue[]]; change:[detail:UvListboxDetail]; search:[query:string] }>()
const query=ref('');const active=ref(0)
function parse(){try{const v=JSON.parse(props.optionsJson);return Array.isArray(v)?v:[]}catch{return[]}}
const source=computed<UvListboxOption[]>(()=>props.options.length?props.options:parse())
const visible=computed(()=>source.value.filter(o=>!query.value||`${o.label} ${o.description||''}`.toLowerCase().includes(query.value.toLowerCase())))
watch(query,v=>emit('search',v))
function selected(value:UvListboxValue){return Array.isArray(props.modelValue)?props.modelValue.includes(value):props.modelValue===value}
function choose(option:UvListboxOption,index:number){if(props.disabled||option.disabled)return;active.value=index;let value:UvListboxValue|UvListboxValue[]=option.value;if(props.multiple){const current=Array.isArray(props.modelValue)?[...props.modelValue]:[];value=selected(option.value)?current.filter(v=>v!==option.value):[...current,option.value]}emit('update:modelValue',value);emit('change',{value,option})}
function key(event:KeyboardEvent){if(!visible.value.length)return;let next=active.value;if(event.key==='ArrowDown')next=Math.min(visible.value.length-1,next+1);else if(event.key==='ArrowUp')next=Math.max(0,next-1);else if(event.key==='Home')next=0;else if(event.key==='End')next=visible.value.length-1;else if((event.key==='Enter'||event.key===' ')&&visible.value[next]){event.preventDefault();choose(visible.value[next],next);return}else return;event.preventDefault();while(visible.value[next]?.disabled&&next!==active.value)next+=event.key==='ArrowUp'?-1:1;active.value=Math.max(0,Math.min(next,visible.value.length-1));(event.currentTarget as HTMLElement).querySelectorAll<HTMLElement>('[role=option]')[active.value]?.scrollIntoView({block:'nearest'})}
</script>
<template><div class="uv-listbox" :class="{'uv-listbox--disabled':disabled}"><label v-if="searchable" class="uv-listbox__search"><span>{{ label }}</span><input v-model="query" type="search" :disabled="disabled" :placeholder="`Search ${label.toLowerCase()}`"></label><span v-else class="uv-listbox__label" :id="`${label}-listbox-label`">{{ label }}</span><div class="uv-listbox__options" role="listbox" :aria-label="searchable?label:undefined" :aria-labelledby="searchable?undefined:`${label}-listbox-label`" :aria-multiselectable="multiple||undefined" :aria-disabled="disabled||undefined" tabindex="0" :style="{maxHeight:`${Math.max(2,size)*2.75}rem`}" :aria-activedescendant="visible[active]?`uv-listbox-option-${active}`:undefined" @keydown="key"><div v-for="(option,index) in visible" :id="`uv-listbox-option-${index}`" :key="option.value" role="option" :aria-selected="selected(option.value)" :aria-disabled="option.disabled||undefined" :class="{'uv-listbox__option--active':index===active}" @click="choose(option,index)" @mousemove="active=index"><strong>{{ option.label }}</strong><span v-if="option.description">{{ option.description }}</span></div><p v-if="!visible.length" class="uv-listbox__empty">No options found.</p></div></div></template>
<style>.uv-listbox{display:grid;gap:.45rem;font:inherit;color:#0f172a}.uv-listbox__label,.uv-listbox__search span{font-weight:600}.uv-listbox__search{display:grid;gap:.4rem}.uv-listbox__search input{padding:.65rem .75rem;border:1px solid var(--uv-color-border,#cbd5e1);border-radius:.5rem;font:inherit}.uv-listbox__options{overflow:auto;padding:.3rem;border:1px solid var(--uv-color-border,#cbd5e1);border-radius:var(--uv-radius-md,.625rem);background:#fff}.uv-listbox [role=option]{display:grid;gap:.15rem;padding:.55rem .65rem;border-radius:.4rem;cursor:pointer}.uv-listbox [role=option]>span{color:#64748b;font-size:.82rem}.uv-listbox [role=option][aria-selected=true]{background:#dbeafe;color:#1d4ed8}.uv-listbox__option--active{outline:2px solid color-mix(in srgb,var(--uv-color-primary,#2563eb) 35%,transparent);outline-offset:-2px}.uv-listbox [aria-disabled=true]{opacity:.45;cursor:not-allowed}.uv-listbox__options:focus-visible{outline:2px solid var(--uv-color-primary,#2563eb);outline-offset:2px}.uv-listbox__empty{margin:.5rem;color:#64748b}.uv-listbox--disabled{opacity:.65}</style>
