<script setup lang="ts">
import { computed, ref } from 'vue'
import type { UvCodeBlockCopyDetail } from './code-block.types'
interface Props { code:string; language?:string; label?:string; copyable?:boolean; wrap?:boolean; lineNumbers?:boolean; highlightLines?:string }
const props=withDefaults(defineProps<Props>(),{language:'text',label:'Code example',copyable:true,wrap:false,lineNumbers:false,highlightLines:''})
const emit=defineEmits<{ copy:[detail:UvCodeBlockCopyDetail] }>()
const copied=ref(false)
const lines=computed(()=>props.code.replace(/\n$/,'').split('\n'))
const highlighted=computed(()=>{const result=new Set<number>();for(const part of props.highlightLines.split(',').map(v=>v.trim()).filter(Boolean)){if(part.includes('-')){const [a,b]=part.split('-').map(Number);for(let n=a;n<=b;n++)result.add(n)}else result.add(Number(part))}return result})
async function copy(){let success=false;try{if(typeof navigator!=='undefined'&&navigator.clipboard){await navigator.clipboard.writeText(props.code);success=true}}catch{success=false}copied.value=success;if(success)setTimeout(()=>{copied.value=false},1500);emit('copy',{code:props.code,success})}
</script>
<template><figure class="uv-code-block" :class="{'uv-code-block--wrap':wrap}" :aria-label="label"><figcaption><span>{{ language }}</span><button v-if="copyable" type="button" @click="copy">{{ copied?'Copied':'Copy code' }}</button></figcaption><pre><code><span v-for="(line,index) in lines" :key="index" class="uv-code-block__line" :class="{'uv-code-block__line--highlight':highlighted.has(index+1)}"><span v-if="lineNumbers" class="uv-code-block__number" aria-hidden="true">{{ index+1 }}</span><span>{{ line || ' ' }}</span></span></code></pre><span class="uv-code-block__sr" aria-live="polite">{{ copied?'Code copied to clipboard':'' }}</span></figure></template>
<style>.uv-code-block{overflow:hidden;margin:0;border:1px solid #334155;border-radius:var(--uv-radius-md,.625rem);background:#0f172a;color:#e2e8f0;font:inherit}.uv-code-block figcaption{display:flex;justify-content:space-between;align-items:center;padding:.45rem .75rem;border-bottom:1px solid #334155;background:#1e293b;color:#cbd5e1;font:500 .8rem/1 system-ui;text-transform:uppercase}.uv-code-block button{border:0;border-radius:.35rem;padding:.35rem .55rem;background:#334155;color:#fff;font:inherit;text-transform:none;cursor:pointer}.uv-code-block pre{overflow:auto;margin:0;padding:.85rem}.uv-code-block code{display:block;font:400 .86rem/1.55 ui-monospace,SFMono-Regular,Consolas,monospace}.uv-code-block__line{display:grid;grid-template-columns:auto 1fr;min-height:1.55em}.uv-code-block__line--highlight{margin-inline:-.85rem;padding-inline:.85rem;background:#2563eb33}.uv-code-block__number{min-width:2.5rem;padding-right:1rem;color:#64748b;text-align:right;user-select:none}.uv-code-block--wrap pre{white-space:pre-wrap;overflow-wrap:anywhere}.uv-code-block__sr{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0 0 0 0)}</style>
