<script setup lang="ts">
import { computed,onBeforeUnmount,onMounted,ref,watch } from 'vue'
import type { UvCarouselChangeDetail,UvCarouselItem } from './carousel.types'
interface Props { items?:UvCarouselItem[]; itemsJson?:string; modelValue?:number; label?:string; autoplay?:boolean; interval?:number; loop?:boolean; showIndicators?:boolean }
const props=withDefaults(defineProps<Props>(),{items:()=>[],itemsJson:'',modelValue:0,label:'Carousel',autoplay:false,interval:5000,loop:true,showIndicators:true})
const emit=defineEmits<{ 'update:modelValue':[value:number]; change:[detail:UvCarouselChangeDetail] }>()
function parse(s:string):UvCarouselItem[]{try{const v=JSON.parse(s);return Array.isArray(v)?v:[]}catch{return[]}}
const list=computed(()=>props.items.length?props.items:parse(props.itemsJson));const paused=ref(false);let timer:ReturnType<typeof setInterval>|undefined
const index=computed(()=>Math.max(0,Math.min(props.modelValue,list.value.length-1)))
function go(i:number){const n=list.value.length;if(!n)return;let x=i;if(props.loop)x=(i+n)%n;else x=Math.max(0,Math.min(n-1,i));emit('update:modelValue',x);emit('change',{index:x,item:list.value[x]})}
function start(){stop();if(props.autoplay&&!paused.value&&list.value.length>1&&typeof window!=='undefined')timer=setInterval(()=>go(index.value+1),Math.max(1000,props.interval))}function stop(){if(timer)clearInterval(timer)}
watch(()=>[props.autoplay,props.interval,props.modelValue,list.value.length,paused.value],start);onMounted(start);onBeforeUnmount(stop)
</script>
<template><section class="uv-carousel" role="region" :aria-label="label" aria-roledescription="carousel" @mouseenter="paused=true" @mouseleave="paused=false" @focusin="paused=true" @focusout="paused=false"><div class="uv-carousel__viewport" aria-live="polite"><article v-if="list[index]" class="uv-carousel__slide" role="group" :aria-label="`${index+1} of ${list.length}`" aria-roledescription="slide"><img v-if="list[index].image" :src="list[index].image" :alt="list[index].alt||''"><div class="uv-carousel__content"><h2>{{ list[index].title }}</h2><p v-if="list[index].description">{{ list[index].description }}</p><a v-if="list[index].href" :href="list[index].href">Learn more</a><slot name="item" :item="list[index]" :index="index" /></div></article></div><button class="uv-carousel__prev" type="button" aria-label="Previous slide" :disabled="!loop&&index===0" @click="go(index-1)">‹</button><button class="uv-carousel__next" type="button" aria-label="Next slide" :disabled="!loop&&index===list.length-1" @click="go(index+1)">›</button><div v-if="showIndicators" class="uv-carousel__dots" role="group" aria-label="Choose slide"><button v-for="(item,i) in list" :key="String(item.id)" type="button" :aria-label="`Go to slide ${i+1}: ${item.title}`" :aria-current="i===index?'true':undefined" @click="go(i)"></button></div></section></template>
<style>.uv-carousel{position:relative;overflow:hidden;border:1px solid var(--uv-color-border,#cbd5e1);border-radius:var(--uv-radius-lg,.875rem);background:var(--uv-color-surface,#fff);color:var(--uv-color-text,#0f172a);font:inherit}.uv-carousel__slide img{display:block;width:100%;aspect-ratio:16/7;object-fit:cover}.uv-carousel__content{padding:1.2rem}.uv-carousel__content :is(h2,p){margin:.2rem 0}.uv-carousel__prev,.uv-carousel__next{position:absolute;top:50%;translate:0 -50%;display:grid;place-items:center;width:2.5rem;height:2.5rem;border:1px solid var(--uv-color-border,#cbd5e1);border-radius:999px;background:rgb(255 255 255/.92);font-size:1.5rem;cursor:pointer}.uv-carousel__prev{left:.75rem}.uv-carousel__next{right:.75rem}.uv-carousel__dots{display:flex;justify-content:center;gap:.45rem;padding:.7rem}.uv-carousel__dots button{width:.65rem;height:.65rem;padding:0;border:0;border-radius:999px;background:#cbd5e1;cursor:pointer}.uv-carousel__dots button[aria-current=true]{background:var(--uv-color-primary,#2563eb)}</style>
